server:
  port: 6080

spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  application:
    name: spring-boot-rabbitmq
  rabbitmq:
    host: 118.31.4.12
    port: 5672
    username: bingo
    password: BFB9fcPHKks
    template:
      mandatory: true


logging:
  level.root: info
  level.spring.boot.rabbitmq: debug
  file:
    name: api.log